"use client";

import type { Metadata } from "next";
import "./globals.css";
import { interFont } from "@/utils/fonts";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdminPage = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body
        className={`${interFont.variable} grid antialiased grid-rows-[auto_1fr_auto] min-h-screen`}
      >
        <Header />

        <main>{children}</main>

        {!isAdminPage && <Footer />}
      </body>
    </html>
  );
}
